POST http://127.0.0.1:1317/skyy/cylinder HTTP/1.1
content-type: application/json

{
    "base_req": {
        "chain_id": "skyyNetwork",
        "from": "skyy14a5vmle5xwjz7tcawcgt0leu3vp90vugt9ugry",
        "gas": "auto"
    },
    "start_time": "2020-09-29T00:00:00Z",
    "expire_time": "2020-09-29T01:00:00Z",
    "location": "42,-70,0' AMSL",
    "radius": "10m",
    "height": "10m"
}